# Generated by Django 6.0.4 on 2026-04-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("topic", models.CharField(max_length=60)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="full_name",
            field=models.CharField(default="Unknown Traveler", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="travelers",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tour",
            name="departure_city",
            field=models.CharField(default="Almaty", max_length=120),
        ),
        migrations.AddField(
            model_name="tour",
            name="duration_text",
            field=models.CharField(default="1 day", max_length=120),
        ),
        migrations.AddField(
            model_name="tour",
            name="hero_label",
            field=models.CharField(default="Nomad Route", max_length=120),
        ),
        migrations.AddField(
            model_name="tour",
            name="image_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tour",
            name="popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tour",
            name="rating",
            field=models.FloatField(default=4.8),
        ),
        migrations.AddField(
            model_name="tour",
            name="region_key",
            field=models.CharField(default="almaty", max_length=60),
        ),
        migrations.AddField(
            model_name="tour",
            name="season_key",
            field=models.CharField(default="all", max_length=60),
        ),
        migrations.AddField(
            model_name="tour",
            name="slug",
            field=models.SlugField(default="tour-legacy", max_length=180, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tour",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
